version: "3.8"

services:
  jenkins:
    build: 
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Allow Jenkins to use Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Skip setup wizard for automation purposes

  flask-app:
    build: 
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py

volumes:
  jenkins_home:
  postgresql_data:
