
version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

volumes:
  jenkins_home:
