version: '3.9'

services:
  jenkins:
    build: ./jenkins-docker
    container_name: testcicd-jenkins-1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    user: root  # Start the container as root

volumes:
  jenkins_home:
